[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 updated_production_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
PORT = "5000"
NIXPACKS_PYTHON_VERSION = "3.11"